export const SIGN_IN = {
  PENDING: 'SIGN_IN_PENDING',
  SUCCESS: 'SIGN_IN_SUCCESS',
  ERROR: 'SIGN_IN_ERROR',
  RESET: 'SIGN_IN_RESET',
};

export const SIGN_UP = {
  PENDING: 'SIGN_UP_PENDING',
  SUCCESS: 'SIGN_UP_SUCCESS',
  ERROR: 'SIGN_UP_ERROR',
  RESET: 'SIGN_UP_RESET',
};

export const LOGOUT = 'LOGOUT';

export const SIGN_IN_USER = 'SIGN_IN_USER';
